
# https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/api-guides/build-system.html#preset-component-variables

PROJECT_NAME := blink
CONFIG_SDK_PYTHON := python3
EXCLUDE_COMPONENTS := openssl protobuf-c protocomm
include $(IDF_PATH)/make/project.mk
