
# https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/api-guides/build-system.html#preset-component-variables

PROJECT_NAME := new-project
CONFIG_SDK_PYTHON := python3

include $(IDF_PATH)/make/project.mk
